apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: johncollins-ingress-resource
spec:
  ingressClassName: nginx
  rules:
  - host: johncollins.ai
    http:
      paths:
      - path: /hello-app
        pathType: Prefix
        backend:
          service:
            name: hello-app
            port:
              number: 8080
